name: Coverage

on: [push, pull_request]

jobs:
  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
