name: Coverage

on: [push, pull_request]

jobs:
  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: $${{ secrets.GH_TOKEN }}
          COVERALLS_REPO_TOKEN: $${{ secrets.COVERALLS_TOKEN }}
